nome=input("Digite o nome do cliente:")
vencimento=int(input("digite o dia do vencimento:"))
mes=input("Digite o mês de vencimento:")
valor=input("Digite o valor da fatura:")
print()
print("Olá,",nome)
print("A sua fatura com vencimento em",vencimento,"de",mes,"no valor de R$",valor,"está fechada.")
